#!/bin/sh

# trap 'pkill -x panel' INT TERM QUIT EXIT

while true ; do

  # start sxhkd
  sxhkd -c ~/.config/sxhkd/sxhkdrc &

  # start bspwm
  bspwm -c /home/rob/.config/bspwm/bspwmrc || break

done
